name: parkops_app
description: "ParkOps - Gestión de mantenimiento"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  signature: ^5.4.0
  mobile_scanner: ^5.2.3
  intl: ^0.18.0
  url_launcher: ^6.2.1
  fl_chart: ^0.70.0   # ← NUEVA DEPENDENCIA
  path_provider: ^2.1.0
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/splash_background.png
  - assets/logo_parkops.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700